### ISSUE TITLE
ESP_wifiManager.WiFi_SSID() and ESP_wifiManager.WiFi_Pass(); never returns a value and if set by other programs never get cleared

### ISSUE THREAD

**Issue by albert8413** [khoih-prog/ESP_WiFiManager#82] opened 2022-06-09 21:45 UTC
### Describe the bug
Using a ESP8266 12F Board the function ESP_wifiManager.WiFi_SSID() and ESP_wifiManager.WiFi_Pass(); always return "". A value is not stored even after setting and connect to SSID in AP mode in the flash. The command Serial.println("ESP Self-Stored: SSID = " + Router_SSID + ", Pass = " + Router_Pass); gives the result:
ESP Self-Stored: SSID = , Pass = 

### Steps to Reproduce

Using any of the included examples and watch the return value

### Expected behavior

Set to the last connected SSID

### Actual behavior
Always empty

### Information

Please ensure to specify the following:

* Platform.io version Core 6.0.2·Home 3.4.1
* ESP8266 Espressiff 8266 4.0.1
 
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
lib_deps = 
    bblanchon/ArduinoJson@^6.19.4
    khoih-prog/ESP_WifiManager@^1.10.2
board_build.ldscript = eagle.flash.4m3m.ld
monitor_speed = 74880
; monitor speed changed in examples to Serial.begin(74880) to read reboot messages from Arduino board in terminal session
board_build.filesystem = littlefs

Just run any of the examples and have a look on the value printed by 
Serial.println("ESP Self-Stored: SSID = " + Router_SSID + ", Pass = " + Router_Pass);
The variables are set by 
  Router_SSID = ESP_wifiManager.WiFi_SSID();
  Router_Pass = ESP_wifiManager.WiFi_Pass();
The routines ESP_wifiManager.WiFi_SSID(); and ESP_wifiManager.WiFi_Pass(); are note working at least on an ESP8266. I will test on an ESP32 next wek

**Comment by khoih-prog** [comment] 2022-06-16 00:01
The library only supports ESP8266 with the correct firmware / board type as in NodeMCU 1.0, etc.

Try a simple program to use WiFi.SSID() and WiFi.psk() to see if OK before wasting more time on ESP12F (desgined for AT commands, etc.)

The WiFi_SSID() and WiFi_Pass() are simply defined to use `WiFi.SSID()` and `WiFi.psk()` as in

https://github.com/khoih-prog/ESP_WiFiManager/blob/69ec6b3e686485f04364277c6172e4a29ea64dce/src/ESP_WiFiManager.hpp#L486-L502

I'm closing the issue as this is not a bug of the library.

**Closed by khoih-prog** 2022-06-16 00:01 UTC
