### ISSUE TITLE
Wifi settings not updated

### ISSUE THREAD

**Issue by Palmeta** [khoih-prog/ESP_WiFiManager#73] opened 2021-11-28 02:55 UTC
Hi, I´m using your library on a nodemcu v3. 
After configuring ssid & password for the first time it can not be changed.
Every time I reboot my device it tries to connect to the first SSID that was configured but since it is out of range it goes into AP mode and has to be reconfigured with the new ssid & password. After clicking save these values are used to connect correctly but on a subsequent reboot it reverts to the first one. The changed values are not persisted.

**Comment by khoih-prog** [comment] 2021-11-28 21:34
Hi,

Thanks for your interest in the library.

I think you didn't use the library correctly somehow in some steps. I suggest you start with the simple yet working [**ConfigOnDoubleReset** example](https://github.com/khoih-prog/ESP_WiFiManager/tree/master/examples/ConfigOnDoubleReset) and follow the instructions in [**So, how it works?**](https://github.com/khoih-prog/ESP_WiFiManager#so-how-it-works).

Also be sure to update the ESP8266 core to **v3.0.2, or at least v2.7.4**, and this library to **v1.7.7**, according to [**Prerequisites**](https://github.com/khoih-prog/ESP_WiFiManager#prerequisites).

As this is not a bug of the library, I'm closing the issue now. If you still have issue, I suggest you ask for help in Arduino or ESP8266 forum.

Good Luck,

**Closed by khoih-prog** 2021-11-28 21:34 UTC
