### ISSUE TITLE
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353

### ISSUE THREAD

**Issue by GeorgeIOT** [khoih-prog/ESP_WiFiManager#68] opened 2021-09-11 16:51 UTC
I get the message: 
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353
When starting my code (ESP32)
I am using version  khoih.prog/ESP_WifiManager@^1.7.4
This happens when the programs starts from a reboot or power up.

ESP_WiFiManager ESP_wifiManager("OpenSprinkler_HTTP");
This code is the line prior to void setup() {

Withing the setup loop I have 
  if (WiFi.status() == WL_CONNECTED) 
  { 
    Serial.print(F("Connected. Local IP: "));
    Serial.println(WiFi.localIP()); 
  }
  else

On boot this will error out 
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353
Setup.....
[WM]
AutoConnect using previously saved SSID/PW, but keep previous settings
[WM] No saved credentials
[WM] Connected after waiting (s) : 0.00
[WM] Local ip = 0.0.0.0
[WM] Connection result:  UNKNOWN
[WM] WiFi.waitForConnectResult Done
[WM] SET AP
[WM] Configuring AP SSID = OpenSprinkler_HTTP
[WM] AP IP address = 192.168.4.1
[WM] HTTP server started
[WM] startConfigPortal : Enter loop
[WM] Connected after waiting (s) : 2.20
[WM] Local ip = 192.168.0.204
[WM] Timed out connection result: WL_CONNECTED

and it will go in to portal mode.
Once it times out, it will connect with saved WiFi data.

I have added this code to the void loop() secction
  if (WiFi.status() == WL_CONNECTED) 
  {}
  else 
  {
    Serial.print(".");
    ESP_wifiManager.autoConnect("OpenSprinkler_HTTP");
  }

This is to force a reconnect if WiFi is lost

**Comment by khoih-prog** [comment] 2021-09-26 03:07
Hi,

Please follow the instruction in [**Issue: Bug report**](https://github.com/khoih-prog/ESP_WiFiManager/issues/new?assignees=&labels=&template=bug_report.md&title=) and at least provide the[**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) as I can 't understand what you're using and can't guess or help anything there.

It's better that you start with the simplest example in [**ESP_WiFiManager examples**](https://github.com/khoih-prog/ESP_WiFiManager/tree/master/examples) to understand the operation of the library, then modify gradually and see **where, why and when** it's starting to give you the issue.

I'm closing the issue now won't reopen until you give enough info so that anyone can easily duplicate the issue or you can prove this is the bug caused by this library.

Good Luck,

**Closed by khoih-prog** 2021-09-26 03:07 UTC
Labels: question, Support
